CREATE ROLE gss_owner PASSWORD 'a' SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN;
CREATE ROLE tana PASSWORD 'a' SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN;
CREATE ROLE ecochu PASSWORD 'a' SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN;
CREATE ROLE pdc PASSWORD 'a' SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN;
CREATE ROLE gn_owner PASSWORD 'a' SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN;
CREATE ROLE webmaster PASSWORD 'a' SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN;
CREATE ROLE ex_owner PASSWORD 'a' SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN;


CREATE DATABASE goo_all;
CREATE DATABASE shinsha;
CREATE DATABASE exchange;
